server:
  #port: '8089'
  port: ${PORT:0}
eureka:
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  jpa:
    #hibernate:
      #ddl-auto: create-drop
    generate-ddl: true
    
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  datasource:
    #url: jdbc:mysql://mysql8:3306/bd_punto_venta?serverTimezone=UTC
    #url: jdbc:mysql://host.docker.internal:3306/bd_punto_venta?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/bd_punto_venta?serverTimezone=UTC
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      pool-name: namePool
    tomcat: 
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15 
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


